fyne-io/fyne-cross

CHANGELOG.md, README.md, docker/CHANGELOG.md, docker/base/Dockerfile, internal/command/android.go, internal/command/command.go, internal/command/context.go, internal/command/context_test.go, internal/command/darwin.go, internal/command/docker.go, internal/command/flag.go, internal/command/ios.go, internal/command/windows.go, internal/command/windows_test.go
This PR adds support for "fyne release"
> Note: since "release" for windows, ios and macOS requires native tools, it is supported only on the relative hosts via the fyne-cli tool.
Fixes #1
=> Adds support for "fyne release"

CHANGELOG.md, internal/command/context_test.go, internal/command/flag.go, internal/command/flag_test.go
This commit fixes the env flag validation that not allow to specify values containg the `=` char like `GOFLAGS=-mod=vendor`
Fixes #5
=> Fix env flag validation

CHANGELOG.md, docker/CHANGELOG.md, docker/base/Dockerfile, docker/linux-386/Dockerfile, docker/linux-arm/Dockerfile, docker/linux-arm64/Dockerfile
This PR is an attempt to update Go to latest versions.
Additionally fixes #19 
To test:
- ensure to have the latest version from develop: `go get github.com/fyne-io/fyne-cross@develop`
- build the docker images locally: `make build-images`
- clear the go cache: `go cache -clean -modcache`
- build your application with fyne-cross
=> Update Go to v1.14.13 and linux deps

internal/command/linux.go
It was listing the supported arches for Windows and thus did not list arm and arm64.
=> Fix listed arches for linux build

.github/workflows/ci.yml, internal/volume/volume.go
This commit fix a regression introduced in d949bc3.
Additionally updates github actions to run on pull requests too
=> Fix volume.JoinPathContainer should not depend on the OS 

docker/base/Dockerfile
The Go update most notable includes a security fix (CVE-2021-3114) for the `crypto/elliptic` package along with the usual bugfixes. Built the docker image locally and tested a Linux build of [wormhole-gui](https://github.com/Jacalz/wormhole-gui).
=> Update Go to v1.14.15 and the fyne cmd command to 2.0.0

internal/command/command.go, internal/command/docker.go
This PR update the package and release command to not use the appID value if empty.
This applies only for target OSes that does not require it.
=> Fix app-id flag regression

README.md, docker/darwin/Dockerfile, internal/command/darwin_image.go, internal/resource/darwin_dockerfile.go
This PR add the possibility to select a specified macOS SDK version from the Xcode Command Line package via the `--sdk-version` flag
Default to auto detection mode that will try to use the newest SDK version avaibable in the Xcode package.
The list of macOS SDKs provided by Xcode can be obtained from the [XCode release notes](https://developer.apple.com/documentation/xcode-release-notes/)
=> Darwin image build: add support for SDK version

README.md
This updates the download macOS tools link to avoid landing on a "this page does not exist" screen.
It targeted this for master as it would have been broken for users otherwise.
=> Fix link to download macOS tools

go.mod, go.sum, internal/cmd/gowindres/main.go, internal/command/command.go, internal/command/darwin_image.go, internal/command/docker.go, internal/command/docker_test.go
The os/exec package on Windows will match the behaviour of cmd.exe by considering the local folder as a primary part of the path. This means that a malicious binary with the same name, in the current folder, would be run instead of the expected binary in the system path. Due to the backwards compat being an issue, this could not be fixed within ox/exec before Go v2. See https://blog.golang.org/path-security for more info.
Related to https://github.com/fyne-io/fyne/pull/2344 but not part of the same effort.
=> Switch to x/sys/execabs for windows security fixes

docker/android/Dockerfile, docker/base/Dockerfile
This PR updates the `android` docker image to use the latest command line tools and updates the Android builds to SDK 30
=> Update docker images: Go v1.17 and Android builds SDK 30 

docker/CHANGELOG.md, docker/base/Dockerfile
Starting from Fyne CLI v2.1.0 the XZ Utils is used to compress unix packages (fyne-io/fyne#1919)
This PR updates the base-image installing the `xz-utils` package
=> [base-image] Add xz-utils package to support unix packaging

docker/CHANGELOG.md, docker/base/Dockerfile
This PR updates the Go version to v1.17.6 into the docker base image.
The following images have been tagged and released on docker hub for testing:
```
1.1-android-22.01.10
1.1-base-22.01.10
1.1-base-freebsd-22.01.10
1.1-base-llvm-22.01.10
1.1-freebsd-amd64-22.01.10
1.1-freebsd-arm64-22.01.10
1.1-linux-386-22.01.10
1.1-linux-arm-22.01.10
1.1-linux-arm64-22.01.10
1.1-windows-22.01.10
```
=> [base-image] Update Go to v1.17.6

CHANGELOG.md, go.mod, go.sum, internal/command/android.go, internal/command/command.go, internal/command/darwin.go, internal/command/flag.go, internal/command/freebsd.go, internal/command/linux.go, internal/command/windows.go, internal/metadata/data.go, internal/metadata/load.go, internal/metadata/load_test.go, internal/metadata/save.go, internal/metadata/save_test.go, internal/metadata/testdata/FyneApp.toml
This PR adds support for the  the FyneApp.toml file
Fixes #78
=> Add support for FyneApp.toml

Makefile, README.md, docker/base/docker-entrypoint.sh, internal/command/docker.go, internal/command/docker_test.go, internal/command/windows.go, internal/command/windows_test.go
- fix the ldflags to be set in GOFLAGS, so there is no problem by
escaping environment variables
- ldflags "-H" should be set with equal sign `-H=windowsgui` instead of
`-H windowsgui'
- add podman detection
- add podman usage: no need to fix uid with gosu, podman has got an
option named "--userns" to set to "keep-id".
=> Propose the ability to use podman

.github/workflows/ci.yml
Opening this as a draft PR to get feedback around building for darwin and ios.
This PR adds an additional job to the GitHub Actions CI Workflow that uses fyne-cross to build the Fyne example [calculator project](https://github.com/fyne-io/calculator/). It also makes some small changes to the linting and testing workflow jobs for consistency and compatibility reasons.
The aim of this additional job is to try and catch integration issues that only occur when using fyne-cross to build an actual app. See this bug report for some context: https://github.com/fyne-io/fyne-cross/issues/100
I'm looking for feedback on the following:
* Is there a clean way to build a Fyne app for darwin or ios targets using the macos GitHub Actions runner? According to the docs the macos running comes with [Xcode …
=> Add CI job to build calculator app

.github/workflows/ci.yml, internal/command/android.go, internal/command/android_test.go, internal/command/command.go, internal/command/container.go, internal/command/context.go, internal/command/darwin.go, internal/command/docker.go, internal/command/docker_test.go, internal/command/freebsd.go, internal/command/ios.go, internal/command/linux.go, internal/command/windows.go, internal/command/windows_test.go, main.go
This is "just" a refactor. As I was working on #98, I realize it would be simpler if there was a bit more potential for reusing code around. I am not sure that all of those change are really idiomatic go and feel like doing a PR that "just" move code around and remove duplicated step will make the next PR easier to move forward.
There should be no functional change. I have only the ability to test with podman at the moment and will be glad if anyone tried with docker.
=> Refactor and reuse code

docker/CHANGELOG.md, docker/base/Dockerfile
This PR release the docker base images on docker hub to have them generally available.
- all: update Go to v1.18.8 
- darwin-image: update LLVM and clang to v14
The following images have been tagged and released on docker hub for testing:
```
1.3-android-2022.11.01
1.3-base-2022.11.01
1.3-base-freebsd-2022.11.01
1.3-base-llvm-2022.11.01
1.3-freebsd-amd64-2022.11.01
1.3-freebsd-arm64-2022.11.01
1.3-linux-386-2022.11.01
1.3-linux-arm-2022.11.01
1.3-linux-arm64-2022.11.01
1.3-web-2022.11.01
1.3-windows-2022.11.01
```
> Note: the `latest` tag will tagged and pushed to docker hub as usual once approved
=> all: update Go to v1.18.8

docker/CHANGELOG.md, docker/base/Dockerfile
This PR release the docker base images on docker hub to have them generally available.
- all: update Go to v1.19.3
- all: update Fyne CLI to v2.2.4
The following images have been tagged and released on docker hub for testing:
```
1.3-android-22.11.14
1.3-base-22.11.14
1.3-base-freebsd-22.11.14
1.3-base-llvm-22.11.14
1.3-freebsd-amd64-22.11.14
1.3-freebsd-arm64
1.3-freebsd-arm64-22.11.14
1.3-linux-386-22.11.14
1.3-linux-arm-22.11.14
1.3-linux-arm64-22.11.14
1.3-web-22.11.14
1.3-windows-22.11.14
```
> Note: the `latest` tag will tagged and pushed to docker hub as usual once approved
=> docker: release 22.11.14

internal/command/command.go
When building, special characters were being created in file paths which were leading to build errors
Fix:
Use `JoinPathContainers` instead of `JoinPathHost` for `dist` and `temp` directiories
=> Fix path issues for windows

go.mod, go.sum, internal/command/container.go
This fix replicates how `fyne package` names the executable for darwin, resulting in the binary being named after the module name which is read from `go.mod` 
An example of an app named "Nomad Toml Name" (set in the `toml`) from a module named "nomad"
Fixes #139
=> Normalise executable name for darwin

internal/command/ios.go
defaultContext is not a reference, but ctx is being copied in it. This means setting Certificate and Profile had actually no effect.
Fixes #(issue)
=> Set certificate and provisioning file before copying ctx.

internal/command/command.go
ios require actually to have any binary running on it to be properly signed and provisioned even when developing not just when pushing stuff to the store.
=> ios developer need to sign and provision there application to run on their tests devices.

internal/command/command.go
This make it possible to compile in a subdirectory using -dir by doing the proper lookup for the Icon specified on the command line.
=> Address issue when using -dir and ctx.Icon can't be found.

.github/workflows/ci.yml, internal/command/flag.go
Windows executable version must have 3 independent digits to be accepted by Windows. Fyne should correct the version, but it would be best to have correct default value.
=> Windows version actually expect 3 digits by default.

internal/command/darwin.go
When running fyne-cross with k8s, it is more efficient to build an image that include the SDK. This patch make it possible for fyne-cross to assume the SDK was packaged in the container.
=> Make it possible to include the SDK in the darwin container.

internal/command/linux.go
As highlighted during the review of PR 1.4.0, we do not need anymore the gles tag for linux arm target. I verified on my PineBook Pro and this work.
=> Remove gles tag now that we rely on fyne to do the right things for us.

internal/command/darwin.go
In the case of using Kubernetes backend, the container isn't started and accessible before we start the image with Prepare. It is simpler to just not try to test when we know what we are doing.
This was suggested during the previous and it is in practice a good solution.
=> Add ability to bypass darwin sdk on image test.

internal/command/context.go, internal/command/docker.go, internal/command/flag.go
This can only be used with vendored directory. It does provide two main benefit. First not setting up network, means that the build will not be able to get any data from the outside. It give you that guarantee that only the source code that is in your vendor directory was used. Second it is faster to setup a container without network.
=> Add ability to disable network in the container while building.

.github/workflows/ci.yml, CHANGELOG.md, README.md, internal/command/context.go, internal/command/docker.go, internal/command/docker_test.go, internal/command/flag.go
fixuid was sub-optimal for builds and spent a considerable amount of time doing unnecessary work.
This PR removes fixuid and instead sets HOME properly so that the zig compiler is able to write its cache files.
Also, if the host user's HOME is set (the general case), the host zip cache directory is mapped to the container for persistent cache between targets and subsequent builds.
Tests updated to work although tests were and continue to be broken on darwin
Fixes #181
=> Remove fixuid, handle user permissions directly

internal/command/command.go
For historical reason go tags can't have space and the quote escaping was actually done by the shell before. Now, as we call fyne directly, we should not quote tags as once passed to go, it breaks things.
Fixes #195
=> Remove unecessary quote

README.md
Windows arm64 has been available a while now but it seems like we missed adding it to the README.md file. This PR targets the `master` branch to make sure that users see it being supported.
On a side not, it would also be cool if [Geoffrey](https://fynelabs.com/geoffrey/) exposed support for it but it is obviously outside of the scope of this PR.
- I did at least make sure to do a local build to double check that it was working :)
=> Update docs with note about Windows arm64 support

README.md
I added 2 lines in the README.md to give better understanding on how non-darwin to darwin compilation works with fyne-cross (see https://github.com/fyne-io/fyne-cross/issues/187)
=> Add more infos on darwin on linux compilation

internal/command/android.go, internal/command/container.go, internal/command/context.go
The keystore need to know the key name to use.
=> Add "key-name" argument to release Android package

.github/dependabot.yaml
This is to turn on dependabot. Currently targetting develop as I will do one PR to get everything once all the last PR are merged here and we can push a new release. Should be shortly.
=> Turn on dependabot.

.github/workflows/ci.yml, internal/command/command.go
This makes the install process more inline with the CI workflow, where both are tested.
=> fix: update install suggestion for missing `fyne` command

internal/command/command.go
I noticed that fyne-cross running on my gitlab CI was taking a very long time to clean directories that don't even exist.  I found that because these cleans are run using docker - it takes a while just to spin up the container to run them.
Fixes #(issue)
=> Performance improvement by avoiding running commands in docker

README.md
This PR updates the Go requirements along with the macOS SDK extraction section
Additionally applies some linter suggestions.
Fixes #282
=> readme: update the requirements and the macos SDK extract section 

internal/metadata/data.go
This commit updates the Fyne metadata to be aligned with v2.5.3
Fixes #284
=> metadata: update Fyne metadata to v2.5.3

go.mod, go.sum, internal/cloud/kubernetes.go, internal/cloud/s3.go, internal/command/command.go, internal/command/darwin_sdk_extract.go, internal/command/kubernetes.go, internal/metadata/load.go, internal/volume/volume.go
This reverts commit ced8fa91138c6018da42b7790cec73e8dd3e8de0.
compress 1.17.9 does not compile with go 1.19
=> Revert "Bump github.com/klauspost/compress from 1.13.4 to 1.17.9"

.github/workflows/ci.yml
Turn back on CI for MacOS and Web target.
=> Enable-macos-ci
